### ISSUE TITLE
programming for kids-easy-35-line 15

### ISSUE THREAD

**Issue by CavenTeddy2013** [jackdoe/programming-for-kids#23]
it should be:

while a > b:

instead of:

whille a > 0:

Caven

**Comment by CavenTeddy2013** [comment]
sorry it should be 
while a >= b:

**Comment by jackdoe** [comment]
thanks! i pushed https://github.com/jackdoe/programming-for-kids/commit/baace80cd4dc77782ecf76a74a2085d3eb51e1ec with your fix
