### ISSUE TITLE
Suggestions for "UNIX PIPES" game

### ISSUE THREAD

**Issue by abetusk** [jackdoe/programming-for-kids#25]
I have a few suggestions for the "UNIX PIPES" games that are all pretty minor so I thought I'd add them into a single issue.

* Card `02` has an example `cat 03.txt | grep "rises" | wc -l` but then the explanation has `grep "raises" ...`. It might be good to either turn `"rises"` into `"raises"` or vice versa to avoid confusion.
* The addition of line numbers to card `03` might help with some of the "win" conditions (`print the 7th line` for example)
* It might be helpful to indicate in the rules card that when presented with a choice of options (say in card `06`) you must pick exactly one
* It might be helpful to indicate in the rules card that options in red are specified by the player (once when the card is played and fixed after the card is in play)

I'm also a bit confused as to what the round structure looks like. Reading the `RULES` card (`01`), I interpret it as each player takes a single card from the top of the deck. The youngest player then picks a task and players try to use their single cards to complete the task.
Once a single round has proceeded with each player playing a single card, the youngest then changes the task, leaving the cards already played in place and the players are then supposed to try to add on additional cards to complete the task.

Was this the intent? An example game might help clarify how you intended the game to be played.

**Comment by jackdoe** [comment]
There is some wiggle room with the rules as the parent/teacher can change them, for example I sometimes ask mid-round 'ok lets do the longest pipe chain now', or 'ok whoever can move shuffle cards within the pipe chain wins, while conserving the output', e.g. cat 03.txt | cat | cat | head -7 | tail -1 i can move it to cat 03.txt | head -7 | cat | tail -1 | cat. I also sometimes just pick a card and say 'ok what will happen if i put tail -5 in the middle of the pipe chain that she has built.

unfortunately the `raises` and `rises` is a typo that i will fix in the pdf

> It might be helpful to indicate in the rules card that options in red are specified by the player (once when the card is played and fixed after the card is in play)

I will clarify that in the next version

> Once a single round has proceeded with each player playing a single card, the youngest then changes the task, leaving the cards already played in place and the players are then supposed to try to add on additional cards to complete the task.

each round resets the cards, so they get reshuffled, i will clarify that in the rules

I will make it clearer in the next version

thanks for the feedback!

**Comment by abetusk** [comment]
Thanks for providing these resources to the community!
