### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by pachacamac** [jackdoe/programming-for-kids#26]
Cool idea for a game! Thanks for taking the time to make cards and all. Just spotted some typos in the cards pdf. I would make a PR but since it's only the pdf that's a bit hard. Anyways, there's "conntents" with double n, you're grepping for "raises" but I think you mean "rises" and so on. I'd let someone have another read through as some of these might be game changing ... pun intended :)

Cheers mate

**Comment by jackdoe** [comment]
thanks!

I am preparing a reprint where i fix the typos
