### ISSUE TITLE
Link not working [punkx.org]

### ISSUE THREAD

**Issue by ghost** [jackdoe/programming-for-kids#29]
The link to the source of the expansion “Process Substitution” on your site seems to be broken. 

404 error: `The 'jackdoe/programming-for-kids' repository doesn't contain the 'projects/unix-pipe-game/ext-01' path in 'master'. `

PS: I really enjoy your card games. Thank you for creating them. :)

**Comment by jackdoe** [comment]
oh thanks for spotting this, its ext-0.1 instead of -01, I just pushed a fix and updated the website

I am glad you enjoy them!
