### ISSUE TITLE
.py to PDF

### ISSUE THREAD

**Issue by colevandersWands** [jackdoe/programming-for-kids#3]
any interest in a script to convert .py files to a highlighted code pdf for printing?  it would create a new pdf with the same name next to each code file.

**Comment by jackdoe** [comment]
idk, in general i dont use syntax highlighting at all `(global-font-lock-mode 0)`, and i teach her without syntax highlighting as well, i dont like how colors make you read in a different way, but maybe other kids will find it beneficial

**Comment by colevandersWands** [comment]
I'd never heard that before, interesting.  What don't you like about how it makes you read the code?

Maybe a script with a flag? `--font-lock`

**Comment by jackdoe** [comment]
just the syntax colors have opinions that are not my opinions neither the writer's opinions :)

for example, just read this:

```c
// the code will run twice
bool panic  = true
while (true) {
    panic = !panic;
    if (panic) break;
}
```

```
// the code will run twice
bool panic  = true
while (true) {
    panic = !panic;
    if (panic) break;
}
```
without syntax highlighting it is much clear what is important (at least for me), with highlighting it seems like the keywords are more prominent than `panic = !panic` 

i think its a personal thing, so i dont have super strong opinion about it, i just dont like it, it pulls my attention away somehow

also comments are just code if you dont use highlighting.

**Comment by colevandersWands** [comment]
I see what you mean about the `panic = !panic`.  Just so used to reading colored code I hadn't thought about it.  thinking back on it I can remember plenty of times when coloring only changed a few key words and makes everything else look less important.

Now I want to try this in class too - [plain text programs](https://github.com/HackYourFutureBelgium/welcome-to-js/tree/91361911f9682b4ecfeb083277e6d85fd6788126)

> also comments are just code if you dont use highlighting.

🧐 ... 👍

**Comment by jackdoe** [comment]
i added [extract.py](../blob/master/extract.py) to extract all code snippets in .txt files into the [examples/](../blob/master/examples) directory

thanks for the suggestion!

**Comment by colevandersWands** [comment]
This is really neat, simple and effective.
