### ISSUE TITLE
Thank you + Chips

### ISSUE THREAD

**Issue by urish** [jackdoe/programming-for-kids#33]
Just found about this book because a friend sent me a link to "Overflow". This is so inspiring! 

My daughter has been playing with breadboard and LEDs since she was 2 yo, but that's been pretty sporadic - whenever she finds some interesting hardware on my table, I try to explain to her how it works / how to use it, and let her play with it. 

I'm now working on Tiny Tapeout, which enables people to design their own digital chip (from a "simple" seven segment decoder up to a functional RISC-V processor), and we the physical chip manufactured. If this can be interesting for your daughter, I can send more info and would also love to give her a free slot.

**Comment by jackdoe** [comment]
wow Tiny Tapeout looks amazing!

it will be super cool to build a simple hardware puzzle of some sort, can you send me more info to jackdoe@fastmail.com?
maybe a hardware tictactoe will be so cool!

as Feynman says: what I can not create, I do not understand

**Comment by urish** [comment]
Thanks! Yeah, let's make it cool. Shooting you an email
