### ISSUE TITLE
Is the 'WARING' typo here deliberate?

### ISSUE THREAD

**Issue by tocklime** [jackdoe/programming-for-kids#34]
https://github.com/jackdoe/programming-for-kids/blob/2790ad42803b65ff34b82ea5f9efcbe924f5e32b/projects/panic/main.py#L34

**Comment by jackdoe** [comment]
haha no its not, but now that i see it its even better with the typo :)

**Comment by jackdoe** [comment]
I actually fixed it, thanks for noticing!
