### ISSUE TITLE
English Language Course 2nd level

### ISSUE THREAD

**Issue by Victordjimbila** [jackdoe/programming-for-kids#45]
http://victordjimbila19.business.blog/2023/10/31/english-language-course-2nd-level/

**Comment by Aaronphall** [comment]
These have nothing to do with the project, why are you adding them?

**Comment by padmick** [comment]
Spam that's hitting lots of projects, id recommend just closing these issues

**Comment by jackdoe** [comment]
i reported and blocked them
sorry for the noise
